name: Maven Package

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
